import tkinter as tk
from PIL import ImageTk, Image
master = tk.Tk()
master.geometry('980x720')
bg = Image.open('assets/Background.png').resize((980,720))
bg_tk = ImageTk.PhotoImage(bg)
canvas = tk.Canvas(master,bg='red')
canvas.pack(fill='both',expand=True)
canvas.create_image(0,0,image=bg_tk,anchor='nw')
start_img = Image.open('assets/play.png').resize((490,270))
start_tk = ImageTk.PhotoImage(start_img)
start_btn = canvas.create_image((480,200),image=start_tk)
editor_img = Image.open('assets/editor.png').resize((490,270))
editor_tk = ImageTk.PhotoImage(editor_img)
editor_btn = canvas.create_image((480,500),image=editor_tk)
canvas.tag_bind(start_btn,"<Button-1>",lambda x : print(x))
canvas.tag_bind(editor_btn,"<Button-1>",lambda x : print(x))
master.mainloop()
